spring.application.name=demo
server.servlet.context-path=/hotelmgmt
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hotelmgmtsys?CreatedatabaseIfnotExist=true
spring.datasource.username=root
spring.datasource.password=123456789

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=false
